### ISSUE TITLE
missing exports

### ISSUE THREAD

**Issue by aulneau** [pcattori/remix-template-vite#3]
`unstable_createViteServer` and `unstable_loadViteServerBuild` are not exported from `@remix-run/dev` on the latest nightly. should I be using a different version?

**Comment by pcattori** [comment]
Looks like this template got shared before we merged the [extensible server PR](https://github.com/remix-run/remix/pull/7682) since Windows CI is failing 😅. Added a [warning in the README](https://github.com/pcattori/remix-template-vite#extensible-server) to call this out for now.

Pretty awesome to see the excitement around this so quickly though! The extensible server support is top priority for me right now, so should land soon.

**Comment by pcattori** [comment]
https://github.com/remix-run/remix/pull/7682 got merged yesterday, so you should be able to try out extensible server now with latest `nightly`!
